### ISSUE TITLE
Enhance output to support gh formatting

### ISSUE THREAD

**Issue by DevKyleS** [AbianG/dactester-action#4]
As a GitHub action it doesnt support gh formatting, which would improve readability and integration support.

* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
* https://cli.github.com/manual/gh_help_formatting

**Comment by AbianG** [comment]
@DevKyleS here's an example of the new output generated:
 
![image](https://user-images.githubusercontent.com/43828066/184106927-85bb73a8-4596-486d-b07d-12a4094f7fac.png)

I think it conforms to the gh formatting standards, as it uses `echo "::error file={$fixed_docfile},title=ERROR::$line"` as specified in [github docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message).

Thank you for the support and suggestions on this one 😄
